language: objective-c
osx_image: xcode9.2
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
matrix:
  include:
    - osx_image: xcode9.2
      env: COVERAGE=code_coverage SDK="iphonesimulator11.2" DESTINATION="name=iPhone 6s,OS=11.2"
    - osx_image: xcode9.2
      env: SDK="iphonesimulator11.2" DESTINATION="name=iPhone 6s,OS=10.3.1"
    - osx_image: xcode9.2
      env: SDK="iphonesimulator11.2" DESTINATION="name=iPhone 6s,OS=9.3"
    - osx_image: xcode9.2
      env: SDK="iphonesimulator11.2" DESTINATION="name=iPhone 6,OS=8.4"
    - osx_image: xcode8.3
      env: SDK="iphonesimulator8.1" DESTINATION="name=iPhone 6,OS=8.1"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install --repo-update
script:
  - set -o pipefail
  - xcodebuild test -workspace MotionAnimator.xcworkspace -scheme MotionAnimatorCatalog -sdk "$SDK" -destination "$DESTINATION" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c;
after_success:
  - if [ "$COVERAGE" == "code_coverage" ]; then
     bash <(curl -s https://codecov.io/bash);
    fi
  - bash <(curl -s https://codecov.io/bash)
